version: "3.7"

x-config:
  &default-config
  # Stuff here applies to all other services.
  # A default network is added so that services can communicate with each other on the same network.
  networks:
    - default

services:
  # This is the application.
  battlemap:
    <<: *default-config
    build:
      context: ./
    ports:
      - 8002:5000
    volumes:
      # This is the source code that the application uses.
      - ./battlemap:/app/battlemap
      # Mount the alembic configuration.
      - ./alembic.ini:/app/alembic.ini
      - ./alembic:/app/alembic
    user: root
    environment:
      # These variables are used by the application to log into postgres.
      # This should be the same as what is in the postgres section.
      POSTGRES_USER: battlemap # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: battlemap # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: battlemap # The PostgreSQL default database (automatically created at first launch)
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
  
  postgres:
    <<: *default-config
    build:
      context: services/postgres
    ports:
      - 5432:5432
    volumes:
      # This is where the database data is stored.
      - postgres_data:/data
    environment:
      # These variables tell the server what the username and password are for the postgres database.
      PGPASSWORD: battlemap
      POSTGRES_PASSWORD: battlemap
      POSTGRES_USER: battlemap
      PGDATA: /data
      # Creates database on startup.
      POSTGRES_DB: battlemap

  # Use this URL to get to pgadmin: http://localhost:8000/browser/
  pgadmin:
    <<: *default-config
    image: 'dpage/pgadmin4:latest'
    ports:
      - 8000:80
    depends_on:
      - postgres
    environment:
      # These variables are used to access the postgres client.
      PGADMIN_DEFAULT_EMAIL: blakelehrbass@gmail.com
      PGADMIN_DEFAULT_PASSWORD: epicpassword
    
  schemaspy:
    <<: *default-config
    image: schemaspy/schemaspy:latest
    depends_on:
      - postgres
    ports:
      - 8001:8000
    user: root
    volumes:
      - ./services/schemaspy/schemaspy.properties:/schemaspy.properties
      - ./schemaspy:/output

# https://herewecode.io/blog/create-a-postgresql-database-using-docker-compose/

volumes:
  postgres_data: