version: "3.7"

services:
  battlemap:
    image: 'postgres:latest'
    build:
      context: ./
    ports:
      - 5432:5432
    volumes:
      - ./battlemap:/app/battlemap
    environment:
      POSTGRES_USER: battlemap # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: battlemap # The PostgreSQL default database (automatically created at first launch)

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: blakelehrbass@gmail.com
      PGADMIN_DEFAULT_PASSWORD: epicpassword
    

# https://herewecode.io/blog/create-a-postgresql-database-using-docker-compose/